export const privacyData = [
  {
    number: "1",
    title: "Introduction",
    content: "ScanSuite (\"we,\" \"our,\" or \"us\") respects your privacy and is committed to protecting it through our compliance with this policy. This Privacy Policy describes the types of information we may collect from you or that you may provide when you use our services and our practices for collecting, using, maintaining, protecting, and disclosing that information."
  },
  {
    number: "2",
    title: "Information We Collect",
    content: "We collect several types of information from and about users of our Services:",
    list: [
      "Personal Information: Name, email address, telephone number, and any other information you provide us.",
      "Usage Data: Information about your internet connection, the equipment you use to access our Services, and usage details.",
      "Scan Results: Data generated by our security tools when scanning authorized targets.",
      "Technical Data: IP addresses, browser type, operating system, and other technical information."
    ]
  },
  {
    number: "3",
    title: "How We Collect Information",
    content: "We collect information:",
    list: [
      "Directly from you when you provide it to us, such as when you register for an account.",
      "Automatically as you navigate through our Services, including usage details, IP addresses, and information collected through cookies.",
      "From third parties, for example, our business partners or service providers."
    ]
  },
  {
    number: "4",
    title: "How We Use Your Information",
    content: "We use information that we collect about you or that you provide to us:",
    list: [
      "To provide, maintain, and improve our Services.",
      "To process and complete transactions, and send you related information.",
      "To send administrative information, such as updates, security alerts, and support messages.",
      "To personalize your experience and deliver content relevant to your interests.",
      "To respond to your comments, questions, and requests and provide customer service.",
      "For compliance with legal obligations and to protect our rights."
    ]
  },
  {
    number: "5",
    title: "Disclosure of Your Information",
    content: "We may disclose personal information that we collect or you provide:",
    list: [
      "To our subsidiaries and affiliates.",
      "To contractors, service providers, and other third parties we use to support our business.",
      "To comply with any court order, law, or legal process.",
      "To enforce our Terms of Service.",
      "If we believe disclosure is necessary to protect the rights, property, or safety of ScanSuite, our customers, or others."
    ]
  },
  {
    number: "6",
    title: "Data Security",
    content: "We have implemented measures designed to secure your personal information from accidental loss and from unauthorized access, use, alteration, and disclosure. Unfortunately, the transmission of information via the internet is not completely secure. Although we do our best to protect your personal information, we cannot guarantee the security of your personal information transmitted to our Services."
  },
  {
    number: "7",
    title: "Your Rights and Choices",
    content: "You may have certain rights regarding your personal information, depending on your location. These may include:",
    list: [
      "Accessing, correcting, or deleting your personal information.",
      "Withdrawing your consent to our processing of your data.",
      "Requesting a copy of your personal data.",
      "Lodging a complaint with a supervisory authority."
    ]
  },
  {
    number: "8",
    title: "Data Retention",
    content: "We retain personal information we collect from you for as long as necessary to fulfill the purposes for which we collected it, including for the purposes of satisfying any legal, accounting, or reporting requirements."
  },
  {
    number: "9",
    title: "Children's Privacy",
    content: "Our Services are not intended for children under 18 years of age, and we do not knowingly collect personal information from children under 18. If we learn we have collected or received personal information from a child under 18, we will delete that information."
  },
  {
    number: "10",
    title: "Changes to Our Privacy Policy",
    content: "We may update our Privacy Policy from time to time. If we make material changes to how we treat our users' personal information, we will notify you through a notice on our website or via email."
  },
  {
    number: "11",
    title: "Contact Information",
    content: "To ask questions or comment about this Privacy Policy and our privacy practices, contact us at: support@scansuite.io."
  }
];